"""R30-A / BUG-5: PG multi-writer race regressions + method completeness.

Pre-R30 the ``create_document`` flow in :class:`PgKnowledgeStore` (and
identically the run_id generated by :func:`runtime.create_run` and
written via ``PgAgentRunStore.upsert_run``) derived the new PK from
``SELECT COUNT(*) + 1`` / ``store.run_count + 1``.  Under multi-writer
Postgres — or even under multiple FastAPI worker processes sharing a
PG backend — two concurrent INSERTs see the same count and the second
one trips a ``UniqueViolation`` / 500.

These tests pin the fix: the stores must produce collision-free
identifiers even when 16 worker threads hammer them concurrently.  The
SQLite leg also runs the same scenario to prove the fix doesn't regress
the legacy path.

R30-A also fills in the :class:`PgKnowledgeStore` method surface that
was discovered missing in R29 (transition_status, mark_parse_failed,
write_chunks, write_qa_log, write_feedback, list_qa_logs, list_feedbacks,
list_documents paginated).  The "method completeness" section covers
those round-trips against both backends.
"""
from __future__ import annotations

import os
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed

import pytest
from ai_employee.agent_platform_api.pg_run_store import PgAgentRunStore
from ai_employee.common_schemas.db import Backend, open_db
from ai_employee.knowledge_api.pg_store import PgKnowledgeStore

# --------------------------------------------------------------------------- #
# DB fixtures
# --------------------------------------------------------------------------- #


def _sqlite_db(tmp_path, name: str):
    return open_db(f"sqlite:///{tmp_path}/{name}.sqlite3", row_factory="dict")


def _pg_db():
    return open_db(os.environ["TEST_POSTGRES_URL"], row_factory="dict")


def _safe_uri(tmp_path, name: str) -> str:
    raw = tmp_path / "raw"
    raw.mkdir(exist_ok=True)
    return str(raw / name)


def _truncate_pg(db) -> None:
    """Wipe shared PG tables so the PG leg starts clean per test."""
    if db.backend != Backend.POSTGRES:
        return
    db.execute("DELETE FROM agent_run_events")
    db.execute("DELETE FROM agent_runs")
    db.execute("DELETE FROM qa_logs")
    db.execute("DELETE FROM feedbacks")
    db.execute("DELETE FROM chunks")
    db.execute("DELETE FROM documents")
    db.commit()


def _knowledge_store(db, tmp_path) -> PgKnowledgeStore:
    s = PgKnowledgeStore(db=db, data_dir=str(tmp_path))
    s.init_schema()
    return s


def _run_store(db) -> PgAgentRunStore:
    s = PgAgentRunStore(db=db)
    s.init_schema()
    return s


# --------------------------------------------------------------------------- #
# BUG-5: concurrent create_document must not collide on the PK.
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "backend_name",
    [
        pytest.param("sqlite", id="sqlite"),
        pytest.param(
            "postgres",
            marks=pytest.mark.skipif(
                not os.getenv("TEST_POSTGRES_URL"), reason="TEST_POSTGRES_URL not set",
            ),
            id="postgres",
        ),
    ],
)
def test_concurrent_create_document_no_pk_collision(
    tmp_path, backend_name: str
) -> None:
    """N concurrent workers, each with its own :class:`PgKnowledgeStore`
    instance (separate in-process locks, sharing the DB), must all
    produce distinct document IDs without raising.

    A single shared store would mask the race because every call would
    serialise on the same ``self._lock``.  By giving each worker its own
    store we exercise the multi-writer path the production chart hits
    when multiple uvicorn workers / replicas share a PG backend.
    """
    if backend_name == "sqlite":
        # SQLite is single-writer; the legacy path serialises inside the
        # process anyway, so a single shared store is the realistic
        # scenario.  Use a fresh DB per test.
        db = _sqlite_db(tmp_path, "k")
        stores = [_knowledge_store(db, tmp_path)]
        N = 1
    else:
        db = _pg_db()
        _truncate_pg(db)
        # 8 independent store objects → 8 independent ``_lock`` instances
        # → real cross-process / cross-replica concurrency on the same
        # Postgres DB.
        N = 8
        stores = [_knowledge_store(db, tmp_path) for _ in range(N)]

    barrier = threading.Barrier(N)
    errors: list[BaseException] = []
    doc_ids: list[str] = []

    def _worker(i: int) -> None:
        try:
            barrier.wait(timeout=5)
            doc_id = stores[i % len(stores)].create_document(
                title=f"t-{i}",
                source_uri=_safe_uri(tmp_path, f"f-{i}"),
                mime_type="text/plain",
                metadata={"i": i},
                acl_tags=[],
                version="v1",
            )
            doc_ids.append(doc_id)
        except BaseException as exc:
            errors.append(exc)

    with ThreadPoolExecutor(max_workers=N) as pool:
        futures = [pool.submit(_worker, i) for i in range(N)]
        for fut in as_completed(futures):
            fut.result()

    assert not errors, f"workers raised: {errors!r}"
    assert len(doc_ids) == N
    assert len(set(doc_ids)) == N, f"duplicate doc_ids detected: {doc_ids}"


@pytest.mark.parametrize(
    "backend_name",
    [
        pytest.param("sqlite", id="sqlite"),
        pytest.param(
            "postgres",
            marks=pytest.mark.skipif(
                not os.getenv("TEST_POSTGRES_URL"), reason="TEST_POSTGRES_URL not set",
            ),
            id="postgres",
        ),
    ],
)
def test_concurrent_upsert_run_no_pk_collision(
    tmp_path, backend_name: str
) -> None:
    """N concurrent threads each upsert a new run; all N must persist
    and the resulting run_ids must be distinct.

    Each thread mints its own ``run_id`` via the platform counter
    generator and passes it in — that's how ``app.create_agent_run``
    feeds the PG store today, so the fix has to land either in the
    generator or in the store.  We pin the contract: the store must
    not collide even when the caller-supplied id happens to repeat.
    """
    if backend_name == "sqlite":
        db = _sqlite_db(tmp_path, "r")
    else:
        db = _pg_db()
        _truncate_pg(db)
    store = _run_store(db)

    N = 16
    barrier = threading.Barrier(N)
    errors: list[BaseException] = []
    run_ids: list[str] = []

    def _worker(i: int) -> None:
        try:
            barrier.wait(timeout=5)
            run_id = f"run_concurrent_{i:03d}"
            store.upsert_run({
                "run_id": run_id,
                "template_id": "knowledge_qa",
                "agent_name": "Knowledge QA",
                "status": "running",
                "trace_id": f"trace-{i}",
                "requested_by": "alice",
                "input": {"i": i},
                "output": {},
                "node_trace": [],
                "tool_calls": [],
                "approval_status": "not_required",
                "resume_from_node": None,
            })
            run_ids.append(run_id)
        except BaseException as exc:
            errors.append(exc)

    with ThreadPoolExecutor(max_workers=N) as pool:
        futures = [pool.submit(_worker, i) for i in range(N)]
        for fut in as_completed(futures):
            fut.result()

    assert not errors, f"workers raised: {errors!r}"
    assert len(run_ids) == N
    assert len(set(run_ids)) == N


def test_upsert_run_assigns_id_when_caller_omits(tmp_path) -> None:
    """The store must accept a payload without ``run_id`` and mint one
    itself, so callers can drop their in-memory counter race entirely.
    """
    if os.getenv("TEST_POSTGRES_URL"):
        db = _pg_db()
    else:
        db = _sqlite_db(tmp_path, "r")
    _truncate_pg(db)
    store = _run_store(db)
    payload = {
        "template_id": "knowledge_qa",
        "agent_name": "Knowledge QA",
        "status": "running",
        "trace_id": "trace-auto",
        "requested_by": "alice",
        "input": {},
        "output": {},
        "node_trace": [],
        "tool_calls": [],
        "approval_status": "not_required",
        "resume_from_node": None,
    }
    run_id = store.upsert_run(payload)  # type: ignore[arg-type]
    assert isinstance(run_id, str) and run_id
    got = store.get_run(run_id)
    assert got is not None
    assert got["run_id"] == run_id


# --------------------------------------------------------------------------- #
# R30-A: PgKnowledgeStore method completeness (R29 leftover).
# Mirrors SQLiteStore; verifies round-trip against both backends.
# --------------------------------------------------------------------------- #


def _knowledge_dbs(tmp_path):
    yield "sqlite", _sqlite_db(tmp_path, "km")
    if os.getenv("TEST_POSTGRES_URL"):
        pg = _pg_db()
        _truncate_pg(pg)
        yield "postgres", pg


def _doc_payload(tmp_path, i: int) -> dict:
    return {
        "title": f"t-{i}",
        "source_uri": _safe_uri(tmp_path, f"f-{i}"),
        "mime_type": "text/plain",
        "metadata": {"author": "ops", "i": i},
        "acl_tags": ["ops-team"],
        "version": "v1",
    }


def test_transition_status_round_trip(tmp_path) -> None:
    for _label, db in _knowledge_dbs(tmp_path):
        store = _knowledge_store(db, tmp_path)
        doc_id = store.create_document(**_doc_payload(tmp_path, 0))
        out = store.transition_status(doc_id, "parsing")
        assert out["parse_status"] == "parsing"
        out = store.transition_status(doc_id, "ready")
        assert out["parse_status"] == "ready"
        out = store.transition_status(doc_id, "published")
        assert out["parse_status"] == "published"


def test_mark_parse_failed_sets_error(tmp_path) -> None:
    for _label, db in _knowledge_dbs(tmp_path):
        store = _knowledge_store(db, tmp_path)
        doc_id = store.create_document(**_doc_payload(tmp_path, 1))
        store.mark_parse_failed(doc_id, "boom", stage="ocr")
        doc = store.get_document(doc_id)
        assert doc["parse_status"] == "parse_failed"
        assert "[ocr] boom" in doc["parse_error"]


def test_write_chunks_marks_ready(tmp_path) -> None:
    for _label, db in _knowledge_dbs(tmp_path):
        store = _knowledge_store(db, tmp_path)
        doc_id = store.create_document(**_doc_payload(tmp_path, 2))
        chunks = [
            {
                "chunk_id": f"{doc_id}_chunk_{i:03d}",
                "chunk_no": i,
                "content": f"content {i}",
                "section_path": "root",
                "table_id": None,
                "row_id": None,
            }
            for i in range(3)
        ]
        embeddings = [[0.1, 0.2, 0.3] for _ in chunks]
        store.write_chunks(
            doc_id=doc_id,
            chunks=chunks,
            embeddings=embeddings,
            embedding_model="bge-m3",
            acl_tags_override=["ops-team"],
        )
        doc = store.get_document(doc_id)
        assert doc["parse_status"] == "ready"
        assert doc["chunk_count"] == 3
        stored = store.get_chunks_for_doc(doc_id)
        assert [c["chunk_no"] for c in stored] == [0, 1, 2]


def test_write_qa_log_and_list(tmp_path) -> None:
    for _label, db in _knowledge_dbs(tmp_path):
        store = _knowledge_store(db, tmp_path)
        store.write_qa_log(
            qa_log_id="qa_001",
            session_id="s1",
            user_id="alice",
            question="q",
            rewritten_query=None,
            knowledge_scopes=["ops-team"],
            retrieved_chunks=[{"chunk_id": "c1", "score": 0.9}],
            answer="a",
            model_name="bge-m3",
            prompt_version="v1",
            confidence=0.7,
            latency_ms=120,
            trace_id="trace-1",
        )
        items, total = store.list_qa_logs(session_id="s1", page=1, page_size=10)
        assert total == 1
        assert items[0]["qa_log_id"] == "qa_001"
        assert items[0]["knowledge_scopes"] == ["ops-team"]
        full = store.get_qa_log("trace-1")
        assert full is not None
        assert full["qa_log_id"] == "qa_001"
        assert full["retrieved_chunks"] == [{"chunk_id": "c1", "score": 0.9}]


def test_write_feedback_and_list(tmp_path) -> None:
    for _label, db in _knowledge_dbs(tmp_path):
        store = _knowledge_store(db, tmp_path)
        fid = store.write_feedback(
            trace_id="trace-1", feedback_type="up", comment="good",
        )
        assert fid.startswith("fb_")
        items, total = store.list_feedbacks(trace_id="trace-1")
        assert total == 1
        assert items[0]["feedback_id"] == fid
        assert items[0]["feedback_type"] == "up"


def test_list_documents_paginated(tmp_path) -> None:
    for _label, db in _knowledge_dbs(tmp_path):
        store = _knowledge_store(db, tmp_path)
        for i in range(5):
            store.create_document(**_doc_payload(tmp_path, i))
        items, total = store.list_documents(page=1, page_size=2)
        assert total == 5
        assert len(items) == 2
        items, total = store.list_documents(page=3, page_size=2)
        assert total == 5
        assert len(items) == 1


def test_list_documents_filter_by_status(tmp_path) -> None:
    for _label, db in _knowledge_dbs(tmp_path):
        store = _knowledge_store(db, tmp_path)
        for i in range(3):
            doc_id = store.create_document(**_doc_payload(tmp_path, i))
            if i == 0:
                store.transition_status(doc_id, "parsing")
                store.transition_status(doc_id, "ready")
                store.transition_status(doc_id, "published")
        published, total = store.list_documents(status="published")
        assert total == 1
        assert published[0]["parse_status"] == "published"
